---
ipaserver_domain: cluster.local
ipaserver_realm: CLUSTER.LOCAL
ipaclient_all_ip_addresses: yes
ipasssd_enable_dns_updates: yes
ipaclient_allow_repair: yes
ipaclient_mkhomedir: yes
ipaclient_ssh_trust_dns: yes
