---
- name: Configure FreeIPA
  hosts: ipaserver
  become: true
  tasks:
    - name: Add sudo rule for admins
      freeipa.ansible_freeipa.ipasudorule:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: admin_sudo
        group:
          - admins
        hostcategory: all
        cmdcategory: all
    - name: Add users
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        first: "{{ item.first }}"
        last: "{{ item.last }}"
        password: "{{ item.password }}"
      loop: "{{ users }}"
    - name: Add users to admins
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: admins
        user: "{{ admins + ['admin'] }}"
