---
- name: Configure Slurm DNS Records
  hosts: ipaserver
  become: true
  tasks:
    - name: Add Slurm DNS Record to IPA DNS Zone
      freeipa.ansible_freeipa.ipadnsrecord:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: _slurmctld._tcp
        zone_name: "{{ ipaserver_domain }}"
        record_type: "SRV"
        srv_port: 6817
        srv_weight: 0
        srv_priority: 0
        srv_target: "{{ hostvars[groups['slurm'][0]]['slurm_master_host'] }}"

- name: Install Slurm Cluster
  hosts: slurm
  become: true
  roles:
    - role: ansible-role-slurm
      state: present
  tags:
    - server

- name: Tweak Slurm Config
  hosts: slurm_master_host, slurm_submit_hosts
  become: true
  tasks:
    - name: Set ReturnToService
      lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: '^ReturnToService=.'
        line: 'ReturnToService=2'
