---
- name: Prepare hostnames
  hosts: [ipaserver, ipareplica, ipaclient]
  become: true
  tasks:
    - name: Wait for all hosts to be up
      ansible.builtin.wait_for_connection:
        timeout: 300
    - name: Remove local hostname local IP mapping
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^(127\.0\.0\.1|::1) (?!localhost)'

- name: Configure IPA Server
  hosts: ipaserver
  become: true
  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present
  tags:
    - server

- name: Configure IPA Replica
  hosts: ipareplica
  become: true
  roles:
    - role: freeipa.ansible_freeipa.ipareplica
      state: present
  tags:
    - replica

- name: Configure IPA Client
  hosts: ipaclient
  become: true
  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
  tags:
    - client
