---
- name: Prepare hostnames
  hosts: [ipaserver, ipareplica, ipaclient]
  become: true
  tasks:
    - name: Remove local hostname local IP mapping
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^(127\.0\.0\.1|::1) (?!localhost)'

- name: Configure IPA Server
  hosts: ipaserver
  become: true
  vars_files:
    - vault.yml
  roles: 
    - role: freeipa.ansible_freeipa.ipaserver
      state: present
  tags:
    - server

- name: Configure IPA Replica
  hosts: ipareplica
  become: true
  vars_files:
    - vault.yml
  roles: 
    - role: freeipa.ansible_freeipa.ipareplica
      state: present
  tags:
    - replica

- name: Configure IPA Client
  hosts: ipaclient
  become: true
  vars_files:
    - vault.yml
  roles: 
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
  tags:
    - client