---
- name: Provision FreeIPA Servers
  hosts: localhost
  vars:
    api_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64633464333264333930663566643634303165383165393065383331356564616263393963373439
          3035373438356630306638356638623435623462303537660a613861386665343835396636313939
          66363735376263656638313562643537393033653336306336643535613965373832326566623634
          3231366639373964310a663064656662363564306338623964653339636262623362333831323630
          3266
  tasks:
  # Master FreeIPA VM
    - name: Create Master VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "ipamaster.cluster.local"
        template_id: 9002
        new_vm_id: 1001
        vm_cores: 2
        vm_memory: 3072
        vm_ip_address: "10.0.1.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaserver"]
  # Replica FreeIPA VM
    - name: Create Replica VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "ipareplica.cluster.local"
        template_id: 9002
        new_vm_id: 1002
        vm_cores: 2
        vm_memory: 3072
        vm_ip_address: "10.0.1.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipareplica"]
    # Slurm Controller VM
    - name: Create Slurm Controller VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "slurmd.cluster.local"
        template_id: 9002
        new_vm_id: 1101
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.2.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm"]
    # Slurm Login VM
    - name: Create Slurm Login VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "login.cluster.local"
        template_id: 9002
        new_vm_id: 1102
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.2.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_submit_hosts", "slurm"]
    # Client VMs
    - name: Create Client VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client1.cluster.local"
        template_id: 9002
        new_vm_id: 2000
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm"]
    - name: Create Client VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client2.cluster.local"
        template_id: 9002
        new_vm_id: 2001
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm"]
    - name: Create Client VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client3.cluster.local"
        template_id: 9002
        new_vm_id: 2002
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.3/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm"]
