---
- name: Provision FreeIPA Servers
  hosts: localhost
  tasks:
  # Master FreeIPA VM
    - name: Create Master VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "ipamaster.cluster.local"
        template_id: 9002
        new_vm_id: 1001
        vm_cores: 2
        vm_memory: 3072
        vm_ip_address: "10.0.1.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaserver", "nfsclient"]
        state: started
  # Replica FreeIPA VM
    - name: Create Replica VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "ipareplica.cluster.local"
        template_id: 9002
        new_vm_id: 1002
        vm_cores: 2
        vm_memory: 3072
        vm_ip_address: "10.0.1.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipareplica", "nfsclient"]
        state: started
    # Slurm Controller VM
    - name: Create Slurm Controller VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "slurmc.cluster.local"
        template_id: 9002
        new_vm_id: 1101
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.2.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm", "nfsclient"]
        state: started
    # Slurm Login VM
    - name: Create Slurm Login VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "login.cluster.local"
        template_id: 9002
        new_vm_id: 1102
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.2.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_submit_hosts", "slurm", "nfsclient"]
        state: started
    # NFS Share VM
    - name: Create NFS VM
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "nfs1.cluster.local"
        template_id: 9002
        new_vm_id: 1201
        vm_cores: 2
        vm_memory: 2048
        vm_ip_address: "10.0.3.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "nfs"]
        state: started
    # Client VMs
    - name: Create Client VM 1
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client1.cluster.local"
        template_id: 9002
        new_vm_id: 2000
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.1/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm", "nfsclient"]
        state: started
    - name: Create Client VM 2
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client2.cluster.local"
        template_id: 9002
        new_vm_id: 2001
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.2/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm", "nfsclient"]
        state: started
    - name: Create Client VM 3
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "client3.cluster.local"
        template_id: 9002
        new_vm_id: 2002
        vm_cores: 4
        vm_memory: 4096
        vm_ip_address: "10.0.200.3/16"
        vm_gateway: "10.0.0.1"
        inventory_types: ["ipaclient", "slurm_workers", "slurm", "nfsclient"]
        state: started
