---
- name: Provision FreeIPA Servers
  hosts: localhost
  tasks:
    - name: Stop VMs
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "{{ item }}"
        force: true
        state: stopped
      loop:
        - "ipamaster.{{ ipaserver_domain }}"
        - "ipareplica.{{ ipaserver_domain }}"
        - "login.{{ ipaserver_domain }}"
        - "nfs1.{{ ipaserver_domain }}"
        - "client1.{{ ipaserver_domain }}"
        - "client2.{{ ipaserver_domain }}"
        - "client3.{{ ipaserver_domain }}"
        - "slurm.{{ ipaserver_domain }}"
      ignore_errors: true
    - name: Delete VMs
      include_role:
        name: proxmox_kvm
      vars:
        proxmox_api_password: "{{ api_password }}"
        vm_name: "{{ item }}"
        force: true
        state: absent
      loop:
        - "ipamaster.{{ ipaserver_domain }}"
        - "ipareplica.{{ ipaserver_domain }}"
        - "login.{{ ipaserver_domain }}"
        - "nfs1.{{ ipaserver_domain }}"
        - "client1.{{ ipaserver_domain }}"
        - "client2.{{ ipaserver_domain }}"
        - "client3.{{ ipaserver_domain }}"
        - "slurm.{{ ipaserver_domain }}"
      ignore_errors: true
